version: 0.2
phase:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g @angular/cli@17  # 确保这一行正确缩进  测试
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - echo 'build error simulation!'
      - ng build -c production
artifacts:
  base-directory: dist/my-angular-project
  files:
    - '**/*'